apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myapp
  namespace: default
spec:
  interval: 1m0s
  path: ./myapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: self
  targetNamespace: default
