---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: self
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: develop
  url: https://github.com/farkasmate/flux-test.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: self
  namespace: default
spec:
  interval: 1m0s
  path: ./config
  prune: true
  sourceRef:
    kind: GitRepository
    name: self
  targetNamespace: default
