apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 20.5.2
  install:
    crds: Create
  interval: 1m0s
  upgrade:
    crds: CreateReplace
  values:
    nodeSelector:
      ingress-ready: "true"
    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443
    service:
      type: NodePort
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: Equal
        effect: NoSchedule
