apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    apps: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: myapp
  template:
    metadata:
      labels:
        apps: myapp
    spec:
      containers:
      - name: myapp
        image: busybox
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
